# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_assistant_pb2 as ai__assistant__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_assistant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIAssistantStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WritePRDescription = channel.unary_unary(
                '/ai_assistant.AIAssistant/WritePRDescription',
                request_serializer=ai__assistant__pb2.WritePRDescriptionRequest.SerializeToString,
                response_deserializer=ai__assistant__pb2.WritePRDescriptionResponse.FromString,
                _registered_method=True)
        self.SmartAutoComplete = channel.unary_unary(
                '/ai_assistant.AIAssistant/SmartAutoComplete',
                request_serializer=ai__assistant__pb2.SmartAutoCompleteRequest.SerializeToString,
                response_deserializer=ai__assistant__pb2.SmartAutoCompleteResponse.FromString,
                _registered_method=True)
        self.ChatGPTForCode = channel.unary_unary(
                '/ai_assistant.AIAssistant/ChatGPTForCode',
                request_serializer=ai__assistant__pb2.ChatGPTForCodeRequest.SerializeToString,
                response_deserializer=ai__assistant__pb2.ChatGPTForCodeResponse.FromString,
                _registered_method=True)
        self.VirtualPairAssistant = channel.stream_stream(
                '/ai_assistant.AIAssistant/VirtualPairAssistant',
                request_serializer=ai__assistant__pb2.ConversationRequest.SerializeToString,
                response_deserializer=ai__assistant__pb2.ConversationResponse.FromString,
                _registered_method=True)


class AIAssistantServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WritePRDescription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SmartAutoComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatGPTForCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VirtualPairAssistant(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIAssistantServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WritePRDescription': grpc.unary_unary_rpc_method_handler(
                    servicer.WritePRDescription,
                    request_deserializer=ai__assistant__pb2.WritePRDescriptionRequest.FromString,
                    response_serializer=ai__assistant__pb2.WritePRDescriptionResponse.SerializeToString,
            ),
            'SmartAutoComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.SmartAutoComplete,
                    request_deserializer=ai__assistant__pb2.SmartAutoCompleteRequest.FromString,
                    response_serializer=ai__assistant__pb2.SmartAutoCompleteResponse.SerializeToString,
            ),
            'ChatGPTForCode': grpc.unary_unary_rpc_method_handler(
                    servicer.ChatGPTForCode,
                    request_deserializer=ai__assistant__pb2.ChatGPTForCodeRequest.FromString,
                    response_serializer=ai__assistant__pb2.ChatGPTForCodeResponse.SerializeToString,
            ),
            'VirtualPairAssistant': grpc.stream_stream_rpc_method_handler(
                    servicer.VirtualPairAssistant,
                    request_deserializer=ai__assistant__pb2.ConversationRequest.FromString,
                    response_serializer=ai__assistant__pb2.ConversationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_assistant.AIAssistant', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_assistant.AIAssistant', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIAssistant(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WritePRDescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_assistant.AIAssistant/WritePRDescription',
            ai__assistant__pb2.WritePRDescriptionRequest.SerializeToString,
            ai__assistant__pb2.WritePRDescriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SmartAutoComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_assistant.AIAssistant/SmartAutoComplete',
            ai__assistant__pb2.SmartAutoCompleteRequest.SerializeToString,
            ai__assistant__pb2.SmartAutoCompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatGPTForCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_assistant.AIAssistant/ChatGPTForCode',
            ai__assistant__pb2.ChatGPTForCodeRequest.SerializeToString,
            ai__assistant__pb2.ChatGPTForCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VirtualPairAssistant(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ai_assistant.AIAssistant/VirtualPairAssistant',
            ai__assistant__pb2.ConversationRequest.SerializeToString,
            ai__assistant__pb2.ConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
